### ISSUE TITLE
Crash on OpenATV 7.0

### ISSUE THREAD

**Issue by Muntadher91** [digiteng/xtra#3]
E2 crashes when click the search button.
Using OpenATV 7.0 and xtraevent 3.5

**Comment by pololoko111** [comment]
If you search by bouquets.

`Traceback (most recent call last):
 
File "/usr/lib/enigma2/python/Plugins/Extensions/xtraEvent/xtra.py", line 522, in search
 self.session.open(selBouquets)

File "/usr/lib/enigma2/python/Plugins/Extensions/xtraEvent/xtra.py", line 1145, in __init__
self.sources = [SelectionEntryComponent(s[0], s[1], 0, (s[0] in ["sources"])) for s in self.bouquets]
 
File "/usr/lib/enigma2/python/Plugins/Extensions/xtraEvent/xtra.py", line 1145, in <listcomp>
 self.sources = [SelectionEntryComponent(s[0], s[1], 0, (s[0] in ["sources"])) for s in self.bouquets]

TypeError: 'NoneType' object is not subscriptable
 [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap object at 0xafec6958>>,('xtraEventAction', 'green')) failed)`
